export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";

export const REQUEST_POKEMONS_PENDING = "REQUEST_ROBOTS_PENDING";
export const REQUEST_POKEMONS_SUCCESS = "REQUEST_ROBOTS_SUCCESS";
export const REQUEST_POKEMONS_FAILED = "REQUEST_ROBOTS_FAILED";
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const GETTING_POKEMON_FAILED = "GETTING_POKEMON_FAILED";
export const GET_CHARACTERISTICS = "GET_CHARACTERISTICS";
export const GET_SPECIES_ERROR = "GET_SPECIES_ERROR";
export const GET_SPECIES = "GET_SPECIES";
